site_name: WLO Knowledge Graph

#theme: readthedocs
theme:
   name: null
   custom_dir: 'cinder'

extra_css:
  - yasgui.min.css

extra_javascript:
  - jquery-3.7.1.min.js
  - yasgui.min.js
  - app.js


nav:
  - Home: index.md
  - Semantische Analyse: annotationen.md
  - Anwendungsbereiche: anwendungen.md
  - Qualitätssicherung: qualitaet.md


copyright: "<div class='footer'><p>created with <a href='https://www.wikidata.org/wiki/Q316'><span>&#10084;</span></a> for <a href='https://its.jointly.info/''>ITsJOINTLY</a> by <a href='https://yovisto.com'>yovisto.com</a> &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='https://yovisto.com/de/impressum/'>Impressum</a> </p></div> <br><img src='https://its.jointly.info/wp-content/uploads/sites/32/2023/09/logos_horizontal-3.svg'><br>"